# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Format-Epoch
version:      0.0801
version_from: lib/DateTime/Format/Epoch.pm
installdirs:  site
requires:
    DateTime:                      0.22
    Math::BigInt:                  1.66

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
